import React, { useState } from 'react';
import { useVault } from '../context/VaultContext';
import { Action, Field, RestorePanel, CloudPanel } from './SettingsModal';
import { downloadFile } from '../services/native';
export default function SetupScreen() {
 const {setupNewVault,completeSetup,error}=useVault();
 const [master,setMaster]=useState(''),[confirm,setConfirm]=useState(''),[key,setKey]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[tab,setTab]=useState('create');
 return <div className="min-h-screen flex items-center justify-center p-4"><div className="w-full max-w-lg bg-surface-900 border border-slate-700 p-5 rounded-3xl space-y-4"><img src="./logo.png" alt="My Key" className="w-20 h-20 rounded-2xl mx-auto"/><h1 className="text-xl font-bold text-center">ยินดีต้อนรับสู่ My Key</h1>{(message||error)&&<p role="alert" className="text-amber-300">{message||error}</p>}
 {key?<><h2 className="font-bold">เก็บ Recovery Key ก่อนเริ่มใช้งาน</h2><p className="text-sm">ใช้กุญแจนี้กับไฟล์สำรองเมื่อจำ Master Password ไม่ได้ จดไว้ในที่ปลอดภัยแยกจากโทรศัพท์</p><code className="block break-all select-all bg-surface-950 p-4 rounded-xl">{key}</code><Action onClick={async()=>{try{await downloadFile('MyKey-Recovery.txt',`My Key Recovery Key\n${key}\nKeep private. A backup file is also required.`, 'text/plain');}catch(e){setMessage(e.message);}}}>บันทึกเอกสารกู้คืน</Action><label className="flex items-center gap-3"><input type="checkbox" checked={saved} onChange={e=>setSaved(e.target.checked)}/>ฉันเก็บกุญแจไว้ในที่ปลอดภัยแล้ว</label><Action disabled={!saved} onClick={completeSetup}>เข้าสู่ My Key</Action></>:<><div className="flex gap-3 text-sm"><button onClick={()=>setTab('create')}>สร้างใหม่</button><button onClick={()=>setTab('restore')}>กู้คืนจากไฟล์</button><button onClick={()=>setTab('cloud')}>กู้คืนจาก Cloud</button></div>{tab==='create'&&<form className="space-y-3" onSubmit={async e=>{e.preventDefault();setMessage('');if(master!==confirm){setMessage('รหัสทั้งสองช่องไม่ตรงกัน');return;}setBusy(true);try{const r=await setupNewVault(master);setKey(r.emergencyKey);setMaster('');setConfirm('');}catch(err){setMessage(err.message);}finally{setBusy(false);}}}><Field aria-label="Master Password" type="password" autoComplete="new-password" placeholder="Master Password อย่างน้อย 12 ตัวอักษร" minLength={12} required value={master} onChange={e=>setMaster(e.target.value)}/><Field aria-label="ยืนยัน Master Password" type="password" autoComplete="new-password" placeholder="ยืนยัน Master Password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/><p className="text-xs text-slate-400">สแกนนิ้วเปิดได้ภายหลังในแอป Android ข้อมูลเข้ารหัสในเครื่อง และ Cloud จะทำงานเมื่อคุณตั้งค่าและเข้าสู่ระบบ</p><Action disabled={busy}>{busy?'กำลังเข้ารหัส…':'สร้างตู้เซฟ My Key'}</Action></form>}{tab==='restore'&&<RestorePanel/>}{tab==='cloud'&&<CloudPanel/>}</>}
 </div></div>;
}
