import React,{useState} from 'react';
import {useVault} from '../context/VaultContext';
import {passwordHealth} from '../services/vaultModel';
import {Action} from './SettingsModal';
export default function VaultTools({onClose,onSelectItem}){
 const v=useVault();const [tab,setTab]=useState('health'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const run=async fn=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const findings=passwordHealth(v.vaultItems);
 return <div className="fixed inset-0 z-50 p-3 bg-black/80 flex items-center justify-center"><div role="dialog" aria-modal="true" aria-label="สุขภาพรหัสและกู้คืน" className="max-w-xl w-full max-h-[90dvh] bg-surface-900 border border-slate-700 rounded-2xl flex flex-col"><div className="p-4 flex justify-between"><h2 className="font-bold">ดูแลตู้เซฟ</h2><button onClick={onClose}>ปิด</button></div><div className="flex overflow-x-auto gap-4 p-4 border-y border-slate-700">{[['health','สุขภาพรหัส'],['trash',`ถังขยะ (${v.trashItems.length})`],['history','ประวัติแก้ไข']].map(([id,label])=><button className={`shrink-0 ${tab===id?'text-emerald-400':''}`} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div><div className="p-4 overflow-y-auto space-y-3">{error&&<p role="alert" className="text-amber-300">{error}</p>}
 {tab==='health'&&<><p className="text-xs text-slate-400">วิเคราะห์ในเครื่องเท่านั้น เป็นการตรวจเบื้องต้น ไม่ใช่การรับรองว่ารหัสไม่เคยรั่ว</p><p>{findings.length} รายการควรตรวจ จาก {v.vaultItems.length} รายการ</p>{findings.map(f=><button key={f.id} className="block text-left p-3 w-full border border-slate-700 rounded-xl" onClick={()=>{onSelectItem(v.vaultItems.find(i=>i.id===f.id));onClose();}}><strong>{f.title}</strong><p className="text-amber-300 text-sm">{f.reasons.join(' • ')}</p></button>)}{!findings.length&&<p>ไม่พบรหัสซ้ำหรือรูปแบบอ่อนตามเกณฑ์เบื้องต้น</p>}</>}
 {tab==='trash'&&<><p className="text-xs text-slate-400">เก็บในตู้เซฟแบบเข้ารหัส ไม่มีการลบถาวรอัตโนมัติ</p>{!v.trashItems.length&&<p>ถังขยะว่าง</p>}{v.trashItems.map(i=><div key={i.id} className="border border-slate-700 rounded-xl p-3 flex justify-between gap-3"><div><strong>{i.title}</strong><p className="text-xs">{new Date(i.deletedAt).toLocaleString('th-TH')}</p></div><Action disabled={busy} onClick={()=>run(()=>v.restoreItem(i.id))}>กู้คืนรายการ</Action></div>)}</>}
 {tab==='history'&&<><p className="text-xs text-slate-400">เก็บ 30 เวอร์ชันล่าสุดต่อรายการ การคืนเวอร์ชันจะเก็บฉบับปัจจุบันไว้ในประวัติก่อน</p>{v.vaultItems.filter(i=>v.history[i.id]?.length).map(i=><details key={i.id} className="border border-slate-700 rounded-xl p-3"><summary>{i.title} ({v.history[i.id].length} เวอร์ชัน)</summary>{v.history[i.id].map((entry,index)=><div key={`${entry.at}-${index}`} className="flex justify-between gap-2 my-3"><span className="text-sm">{new Date(entry.at).toLocaleString('th-TH')}<br/>{entry.item.title}</span><Action disabled={busy} onClick={()=>run(()=>v.restoreHistory(i.id,index))}>คืนเวอร์ชันนี้</Action></div>)}</details>)}{!v.vaultItems.some(i=>v.history[i.id]?.length)&&<p>ยังไม่มีประวัติแก้ไข</p>}</>}
 </div></div></div>;
}
